
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-team-a"
spec:
  namespaceSelector: 
   matchLabels:
    kubernetes.io/metadata.name: team-a # match all.
  preemption:
    reclaimWithinCohort: LowerPriority
    withinClusterQueue: LowerPriority
  resourceGroups:
  - coveredResources: [ "cpu", "memory", "nvidia.com/gpu", "ephemeral-storage" ]
    flavors:
    - name: l4-spot
      resources:
      - name: "cpu"
        nominalQuota: 72
      - name: "memory"
        nominalQuota: 288Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 6
      - name: "ephemeral-storage"
        nominalQuota: 200Gi
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 100
      - name: "memory"
        nominalQuota: 1000Gi
  

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-team-b"
spec:
  namespaceSelector: 
    matchLabels:
     kubernetes.io/metadata.name: team-b
  preemption:
    reclaimWithinCohort: LowerPriority
    withinClusterQueue: LowerPriority
  resourceGroups:
  - coveredResources: [ "cpu", "memory", "nvidia.com/gpu", "ephemeral-storage" ]
    flavors:
    - name: a3-mega-reg
      resources:
      - name: "cpu"
        nominalQuota: 1000
      - name: "memory"
        nominalQuota: 9999Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 1000
      - name: "ephemeral-storage"
        nominalQuota: 10000Gi
    
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-team-c"
spec:
  namespaceSelector: 
    matchLabels:
     kubernetes.io/metadata.name: team-c
  preemption:
    reclaimWithinCohort: LowerPriority
    withinClusterQueue: LowerPriority
  resourceGroups:
  - coveredResources: [ "cpu", "memory", "nvidia.com/gpu", "ephemeral-storage" ]
    flavors:
    - name: a3-mega-reg
      resources:
      - name: "cpu"
        nominalQuota: 1000
      - name: "memory"
        nominalQuota: 9999Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 1000
      - name: "ephemeral-storage"
        nominalQuota: 10000Gi
    - name: l4-spot
      resources:
      - name: "cpu"
        nominalQuota: 1000
      - name: "memory"
        nominalQuota: 1000Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 99
      - name: "ephemeral-storage"
        nominalQuota: 10000Gi

---
  apiVersion: kueue.x-k8s.io/v1beta1
  kind: LocalQueue
  metadata:
    namespace: team-a # LocalQueue under llm namespace 
    name: team-a-queue
  spec:
    clusterQueue: cq-team-a # Point to the ClusterQueue
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: team-b # LocalQueue under llm namespace 
  name: team-b-queue
spec:
  clusterQueue: cq-team-b # Point to the ClusterQueue
---

apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: team-c # LocalQueue under llm namespace 
  name: team-c-queue
spec:
  clusterQueue: cq-team-c # Point to the ClusterQueue