apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: ccc-tpu
spec:
  priorities:
  - spot: true
    tpu:
      type: tpu-v6e-slice
      count: 4
      topology: 2x4
  nodePoolAutoCreation:
    enabled: true